language: python
env:
    - TOX_ENV=py27
    - TOX_ENV=py32
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=pypy
    - TOX_ENV=pypy3
    - TOX_ENV=docs
    - TOX_ENV=flake8
    - TOX_ENV=coverage
install:
    - pip install tox
    - pip install coveralls
    - mkdir influxdb_install
    - wget https://s3.amazonaws.com/influxdb/influxdb_0.9.4_amd64.deb
    - dpkg -x influxdb_*_amd64.deb influxdb_install
script:
    - export INFLUXDB_PYTHON_INFLUXD_PATH=$(pwd)/influxdb_install/opt/influxdb/versions/0.9.4/influxd
    - travis_wait 30 tox -e $TOX_ENV
after_success:
    - if [ "$TOX_ENV" == "coverage" ] ; then coveralls; fi
notifications:
    email: false

sudo: false

# Travis caching
cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
