language: python
env:
    - TOX_ENV=py27
    - TOX_ENV=py32
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=pypy
    - TOX_ENV=pypy3
    - TOX_ENV=docs
    - TOX_ENV=flake8
    - TOX_ENV=coverage
install:
    - sudo pip install tox
    - sudo pip install coveralls
    - wget http://get.influxdb.org/influxdb_0.9.0-rc25_amd64.deb && sudo dpkg -i influxdb_0.9.0-rc25_amd64.deb
script:
    - travis_wait tox -e $TOX_ENV
after_success:
    - if [ "$TOX_ENV" == "coverage" ] ; then coveralls; fi
notifications:
    email: false
