language: python
python:
- 'pypy3'
- 'pypy'
- '3.4'
- '3.3'
- '3.2'
- '2.7'
install:
- travis_retry pip install -r requirements.txt
- travis_retry pip install -r test-requirements.txt
script: nosetests
deploy:
  provider: pypi
  user: errplane
  password:
    secure: C20cSqrCtd7Ng2oxSy9YSQS72aeqMjrRaZTYKIIF4eSR4JzCawasFhof6Pq/mUqx6fJCBTZ7yMUqfK22JAQ2iUoUnBF04IHASR3iwqjdCRbXGtzX1J9Bw//6iCHBE5fgGEHQc8Mw5wKDIy5RvbjiR9ADCW/cIlpVSF9QzH/RA24=
  on:
    tags: true
    repo: influxdb/influxdb-python
